FROM mazamascience/airsensorshiny:1.3.7

LABEL maintainer="hans@mazamascience.com" \
      maintainer="jon@mazamascience.com"

LABEL description="AirSensorShiny Docker Image"

################################################################################
# install software / cleanup

# Remove sample apps
RUN rm -rf /srv/shiny-server/

################################################################################
# app

# Copy app
COPY app /srv/shiny-server/app

# Copy index
COPY src/index.html /srv/shiny-server/

# Allow readable files
RUN chmod -R 755 /srv/shiny-server/

# Port
EXPOSE 3838

# Run
CMD ["/usr/bin/shiny-server.sh"]
