FROM mazamascience/airsensordataviewer:0.9.2

LABEL maintainer="hans@mazamascience.com" \
      maintainer="jon@mazamascience.com"

LABEL description="AirSensor DataViewer Docker Image"

################################################################################
# install software / cleanup

# Remove sample apps
RUN rm -rf /srv/shiny-server/

################################################################################
# app

# Copy app
COPY . /srv/shiny-server

# Allow readable files
RUN chmod -R 755 /srv/shiny-server/inst/app

# Port
EXPOSE 3838

# Run
CMD ["/usr/bin/shiny-server.sh"]
